version: '3.8'

services:
  auth:
    build: ./auth
    env_file:
    - ./auth/.env
    platform: linux/amd64
    depends_on:
      - mongo-auth
    networks:
      - ercp-network
    expose:
      - "3000" # 내부에서만 접근 가능 (gateway용)

  event:
    build: ./event
    env_file:
    - ./event/.env
    platform: linux/amd64
    depends_on:
      - mongo-event
    networks:
      - ercp-network
    expose:
      - "3000" # 내부에서만 접근 가능 (gateway용)

  gateway:
    build: ./gateway
    env_file:
    - ./gateway/.env
    platform: linux/amd64
    ports:
      - "3000:3000" # 오직 gateway만 외부 노출
    networks:
      - ercp-network

  mongo-auth:
    image: mongo:6.0
    platform: linux/amd64
    container_name: mongo-auth
    restart: always
    volumes:
      - ./mongo-auth-data:/data/db
    networks:
      - ercp-network

  mongo-event:
    image: mongo:6.0
    platform: linux/amd64
    container_name: mongo-event
    restart: always
    volumes:
      - ./mongo-event-data:/data/db
    networks:
      - ercp-network

networks:
  ercp-network:
    driver: bridge
